/**
 * Builds release binaries: `pwr` (CLI) and `pwr-agent` (daemon with Studio embedded) for every
 * supported platform, plus SHA256SUMS. Usage: `bun scripts/release.ts [version]`
 * (defaults to the root package.json version). Output: dist/release/.
 */
import { createHash } from "node:crypto";
import {
  copyFileSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { join, relative } from "node:path";

const ROOT = join(import.meta.dir, "..");
const OUT = join(ROOT, "dist", "release");
const STUDIO_DIST = join(ROOT, "apps", "studio", "dist");
const MANIFEST = join(ROOT, "apps", "agent", "src", "platform", "studio-assets.ts");
const TARGETS = ["darwin-arm64", "darwin-x64", "linux-x64", "linux-arm64"] as const;

const packageVersion = (): string => {
  const parsed: unknown = JSON.parse(readFileSync(join(ROOT, "package.json"), "utf8"));
  if (
    parsed &&
    typeof parsed === "object" &&
    "version" in parsed &&
    typeof parsed.version === "string"
  )
    return parsed.version;
  throw new Error("Root package.json has no version");
};

const version = (Bun.argv[2] ?? packageVersion()).replace(/^v/, "");
if (!/^\d+\.\d+\.\d+(-[\w.]+)?$/.test(version)) throw new Error(`Invalid version: ${version}`);

/** Run a command from the repo root, failing the release on a non-zero exit. */
const run = async (cmd: string[], env: Record<string, string> = {}) => {
  const proc = Bun.spawn(cmd, {
    cwd: ROOT,
    stdout: "inherit",
    stderr: "inherit",
    env: { ...process.env, ...env },
  });
  if ((await proc.exited) !== 0) throw new Error(`Failed: ${cmd.join(" ")}`);
};

/** Every file under a directory, as paths relative to it. */
const walk = (dir: string): string[] =>
  readdirSync(dir).flatMap((name) => {
    const path = join(dir, name);
    return statSync(path).isDirectory() ? walk(path).map((p) => join(name, p)) : [name];
  });

/** Generate the embedded-asset manifest the compiled agent serves Studio from. */
const writeStudioManifest = (): void => {
  const files = walk(STUDIO_DIST).sort();
  if (!files.includes("index.html")) throw new Error("Studio build is missing index.html");
  const imports = files.map(
    (file, i) =>
      `import f${i} from ${JSON.stringify(relative(join(MANIFEST, ".."), join(STUDIO_DIST, file)))} with { type: "file" };`,
  );
  const entries = files.map(
    (file, i) => `  ${JSON.stringify(`/${file.split("\\").join("/")}`)}: f${i},`,
  );
  writeFileSync(
    MANIFEST,
    `// Generated by scripts/release.ts; restored to an empty stub after the build.\n${imports.join("\n")}\n\n/** URL path to embedded file path. */\nexport const embeddedStudio: Record<string, string> = {\n${entries.join("\n")}\n};\n`,
  );
};

const stub = readFileSync(MANIFEST, "utf8");
rmSync(OUT, { recursive: true, force: true });
mkdirSync(OUT, { recursive: true });
try {
  // 1. Frontend with the release version baked in.
  await run(["bun", "run", "--cwd", "apps/studio", "build"], { PWR_VERSION: version });
  writeStudioManifest();
  // 2. One CLI and one agent binary per platform.
  const define = ["--define", `__PWR_VERSION__=${JSON.stringify(version)}`];
  for (const target of TARGETS) {
    for (const [name, entry] of [
      ["pwr", "apps/cli/src/index.ts"],
      ["pwr-agent", "apps/agent/src/index.ts"],
    ] as const)
      await run([
        "bun",
        "build",
        "--compile",
        "--minify",
        `--target=bun-${target}`,
        ...define,
        entry,
        "--outfile",
        join(OUT, `${name}-${target}`),
      ]);
  }
} finally {
  writeFileSync(MANIFEST, stub);
}

// 3. License terms and third-party notices travel with every release.
for (const file of ["LICENSE", "THIRD_PARTY_NOTICES.txt"])
  copyFileSync(join(ROOT, file), join(OUT, file));

// 4. Checksums for install.sh verification.
const sums = readdirSync(OUT)
  .filter((file) => file.startsWith("pwr"))
  .sort()
  .map(
    (file) =>
      `${createHash("sha256")
        .update(readFileSync(join(OUT, file)))
        .digest("hex")}  ${file}`,
  );
writeFileSync(join(OUT, "SHA256SUMS"), `${sums.join("\n")}\n`);
console.log(`Built pwr ${version}:\n${sums.join("\n")}`);
